<?php

use DataTypeEdtf\Form\Element\Edtf as EdtfElement;

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $query
 */

$plugins = $this->getHelperPluginManager();
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->headLink()
    ->appendStylesheet($assetUrl('css/data-type-edtf.css', 'DataTypeEdtf'));

$edtfGteSelect = $this->edtfPropertySelect([
    'name' => 'edtf[gte][pid]',
    'attributes' => [
        'aria-label' => $this->translate('Property'),
        'id' => 'edtf-on-after-pid',
        'class' => 'chosen-select',
        'value' => $query['edtf']['gte']['pid'] ?? null,
    ],
    'options' => [
        'edtf_data_type' => 'date',
    ],
]);

$edtfLteSelect = $this->edtfPropertySelect([
    'name' => 'edtf[lte][pid]',
    'attributes' => [
        'aria-label' => $this->translate('Property'),
        'id' => 'edtf-on-before-pid',
        'class' => 'chosen-select',
        'value' => $query['edtf']['lte']['pid'] ?? null,
    ],
    'options' => [
        'edtf_data_type' => 'date',
    ],
]);
?>

<?php if ($edtfGteSelect): ?>
<div class="field" id="edtf-on-after">
    <div class="field-meta">
        <label for=""><?= $translate('Date comes on or after') ?></label>
    </div>
    <div class="inputs">
        <?php
        echo $edtfGteSelect;
        $element = new EdtfElement('edtf[gte][val]');
        $element->setValue($query['edtf']['gte']['val'] ?? null);
        echo $this->formElement($element);
        ?>
    </div>
</div>
<?php endif; ?>

<?php if ($edtfLteSelect): ?>
<div class="field" id="edtf-on-before">
    <div class="field-meta">
        <label for=""><?= $translate('Date comes on or before') ?></label>
    </div>
    <div class="inputs">
        <?php
        echo $edtfLteSelect;
        $element = new EdtfElement('edtf[lte][val]');
        $element->setValue($query['edtf']['lte']['val'] ?? null);
        echo $this->formElement($element);
        ?>
    </div>
</div>
<?php endif; ?>
