<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Laminas\Form\ElementInterface $element
 */

$plugins = $this->getHelperPluginManager();
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$formText = clone($this->plugin('formText'));
$formText->addTranslatableAttribute('aria-label');

$this->headLink()
    ->appendStylesheet($assetUrl('css/data-type-edtf.css', 'DataTypeEdtf'));
$this->headScript()
    ->appendFile($assetUrl('vendor/edtf/edtf.js', 'DataTypeEdtf'))
    ->appendFile($assetUrl('js/data-type-edtf.js', 'DataTypeEdtf'));
?>

<div class="edtf">
    <div class="error invalid-value"
        data-invalid-message="<?= $escapeAttr($translate('Invalid value: %s')) ?>"
        data-custom-validity="<?= $escapeAttr($translate('Value must be an EDTF datetime')) ?>">
    </div>
    <div class="edtf-datetime-inputs">
        <div class="edtf-inputs">
            <?= $formText($element->getValueElement()) ?>
        </div>
    </div>
    <script>
        $(document).ready(function(){
            DataTypeEdtf.listen();
        });
    </script>
</div>
