<?php
use DataTypeEdtf\Form\Element\Edtf as EdtfElement;

$this->headLink()->appendStylesheet($this->assetUrl('css/edtf-data-type.css', 'DataTypeEdtf'));

$edtfGteSelect = $this->edtfPropertySelect([
    'name' => 'edtf[date][gte][pid]',
    'attributes' => [
        'aria-label' => $this->translate('Property'),
        'id' => 'edtf-on-after-pid',
        'class' => 'chosen-select',
        'value' => $query['edtf']['gte']['pid'] ?? null,
    ],
    'options' => [
        'edtf_data_type' => 'date',
    ],
]);

$edtfLteSelect = $this->edtfPropertySelect([
    'name' => 'edtf[date][lte][pid]',
    'attributes' => [
        'aria-label' => $this->translate('Property'),
        'id' => 'edtf-on-before-pid',
        'class' => 'chosen-select',
        'value' => $query['edtf']['lte']['pid'] ?? null,
    ],
    'options' => [
        'edtf_data_type' => 'date',
    ],
]);
?>

<?php if ($edtfGteSelect): ?>
<div class="field" id="edtf-on-after">
    <div class="field-meta">
        <label for=""><?php echo $this->translate('Date comes on or after'); ?></label>
    </div>
    <div class="inputs">
        <?php
        echo $edtfGteSelect;
        $element = new EdtfElement('edtf[date][gte][val]');
        $element->setValue($query['edtf']['gte']['val'] ?? null);
        echo $this->formElement($element);
        ?>
    </div>
</div>
<?php endif; ?>

<?php if ($edtfLteSelect): ?>
<div class="field" id="edtf-on-before">
    <div class="field-meta">
        <label for=""><?php echo $this->translate('Date comes on or before'); ?></label>
    </div>
    <div class="inputs">
        <?php
        echo $edtfLteSelect;
        $element = new EdtfElement('edtf[date][lte][val]');
        $element->setValue($query['edtf']['lte']['val'] ?? null);
        echo $this->formElement($element);
        ?>
    </div>
</div>
<?php endif; ?>
