<?php

namespace DoctrineProxies\__CG__\DataTypeEdtf\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Edtf extends \DataTypeEdtf\Entity\Edtf implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'resource', 'property', 'valueMinDate', 'valueMinTime', 'valueMaxDate', 'valueMaxTime'];
        }

        return ['__isInitialized__', 'id', 'resource', 'property', 'valueMinDate', 'valueMinTime', 'valueMaxDate', 'valueMaxTime'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Edtf $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setResource(\Omeka\Entity\Resource $resource): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResource', [$resource]);

        parent::setResource($resource);
    }

    /**
     * {@inheritDoc}
     */
    public function getResource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResource', []);

        return parent::getResource();
    }

    /**
     * {@inheritDoc}
     */
    public function setProperty(\Omeka\Entity\Property $property): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProperty', [$property]);

        parent::setProperty($property);
    }

    /**
     * {@inheritDoc}
     */
    public function getProperty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProperty', []);

        return parent::getProperty();
    }

    /**
     * {@inheritDoc}
     */
    public function setValueMinDate(int $valueMinDate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValueMinDate', [$valueMinDate]);

        parent::setValueMinDate($valueMinDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getValueMinDate(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValueMinDate', []);

        return parent::getValueMinDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setValueMinTime(int $valueMinTime): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValueMinTime', [$valueMinTime]);

        parent::setValueMinTime($valueMinTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getValueMinTime(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValueMinTime', []);

        return parent::getValueMinTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setValueMaxDate(int $valueMaxDate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValueMaxDate', [$valueMaxDate]);

        parent::setValueMaxDate($valueMaxDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getValueMaxDate(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValueMaxDate', []);

        return parent::getValueMaxDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setValueMaxTime(int $valueMaxTime): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValueMaxTime', [$valueMaxTime]);

        parent::setValueMaxTime($valueMaxTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getValueMaxTime(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValueMaxTime', []);

        return parent::getValueMaxTime();
    }

    /**
     * {@inheritDoc}
     */
    public function getResourceId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourceId', []);

        return parent::getResourceId();
    }

}
