<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 */
?>

<?= $this->formRow($elementPropertyId) ?>
<?= $this->formRow($elementValues) ?>
<?= $this->partial('show-all', [
    'label' => $this->translate('Show all available values.'),
    'url' => $this->url('admin/site/slug/faceted-browse-edtf', ['controller' => 'index', 'action' => 'timestamp-values'], true),
    'queryParams' => [
        'property_id' => '#date-after-property-id',
    ],
]) ?>
